version: '3'

services:
  app:
    build: .
    depends_on:
      - redis
    command: uvicorn app.main:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./app.env

  redis:
    image: redis
    ports:
      - "6379:6379"